#!/usr/bin/env python
import sys, re
from subprocess import check_output

if sys.version_info[0] > 2:
    print 'Python version > 2, ignoring commit check'
    sys.exit(0)

msg = check_output(['cat', sys.argv[1]]).strip()
regex = r'(refs|closes|fixes) TS-\d+'
if re.search(regex, msg) == None:
    print 'Commit needs ticket reference\n'
    print 'Commit Message Contents: \n'
    print msg
    sys.exit(1)

regex = r'TEST PLAN:'
if re.search(regex, msg, re.IGNORECASE) == None:
    print 'Commit needs test plan\n'
    print 'Commit Message Contents: \n'
    print msg
    sys.exit(1)
